package ua.quietlymavenplugin.render;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.*;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import ua.quietlymavenplugin.render.config.QuietlyPluginConfig;
import ua.quietlymavenplugin.render.javaparser.ImportManager;

import java.util.List;

public class CrudTestAstBuilder
{

   private static final List<String> CRUD_TEST_IMPORTS = List.of(
            "org.junit.jupiter.api.Test",
            "io.quarkus.test.security.TestSecurity",
            "io.quarkus.test.junit.QuarkusTest",
            "io.quarkus.test.common.http.TestHTTPEndpoint",
            "org.junit.jupiter.api.BeforeEach",
            "jakarta.transaction.Transactional",
            "ua.quietlytestsupport.support.SqlUtils",
            "java.io.IOException",
            "org.junit.jupiter.api.Assertions",
            "io.restassured.RestAssured",
            "io.restassured.response.Response"
   );

   public static CompilationUnit createCompilationUnit(
            Class<?> entityClass,
            String rootPkg,
            String serviceClassName,
            QuietlyPluginConfig config
   )
   {
      String entityName = entityClass.getSimpleName();
      CompilationUnit cu = new CompilationUnit();
      cu.setPackageDeclaration(rootPkg);

      ImportManager imports = new ImportManager(cu);
      imports.add_imports(CRUD_TEST_IMPORTS);
      if (config.disabledByDefault())
      {
         imports.add_import("org.junit.jupiter.api.Disabled");
      }
      imports.add_import(entityClass.getName());
      imports.add_import(serviceClassName);

      ClassOrInterfaceDeclaration classDecl = cu.addClass(entityName + "CrudTest").setPublic(true);
      classDecl.addAnnotation(new MarkerAnnotationExpr("QuarkusTest"));

      NormalAnnotationExpr testEndpointAnnotation = new NormalAnnotationExpr();
      testEndpointAnnotation.setName("TestHTTPEndpoint");
      ClassOrInterfaceType serviceType = StaticJavaParser.parseClassOrInterfaceType(
               config.resolveServiceName(entityClass));
      testEndpointAnnotation.addPair("value", new ClassExpr(serviceType));
      classDecl.addAnnotation(testEndpointAnnotation);

      classDecl.addMember(FilterTestAstBuilder.buildBeforeEachMethod(entityClass));
      classDecl.addMember(buildListMethod(config.disabledByDefault()));
      classDecl.addMember(buildGetMissingMethod(config.disabledByDefault()));

      return cu;
   }

   public static MethodDeclaration buildListMethod(boolean disabledByDefault)
   {
      MethodDeclaration method = parseMethod("""
               @Test
               @TestSecurity(user = "test")
               public void list_endpoint_returns_success_test() {
                   Response response = RestAssured.given()
                           .when()
                           .get()
                           .then()
                           .extract()
                           .response();
                   Assertions.assertEquals(200, response.statusCode());
               }
               """);
      method.setJavadocComment("@quietly-generated crud=\"list\"");
      addDisabled(method, disabledByDefault);
      return method;
   }

   public static MethodDeclaration buildGetMissingMethod(boolean disabledByDefault)
   {
      MethodDeclaration method = parseMethod("""
               @Test
               @TestSecurity(user = "test")
               public void get_missing_entity_returns_not_found_test() {
                   Response response = RestAssured.given()
                           .pathParam("id", Long.MAX_VALUE)
                           .when()
                           .get("/{id}")
                           .then()
                           .extract()
                           .response();
                   Assertions.assertEquals(404, response.statusCode());
               }
               """);
      method.setJavadocComment("@quietly-generated crud=\"get-missing\"");
      addDisabled(method, disabledByDefault);
      return method;
   }

   private static MethodDeclaration parseMethod(String code)
   {
      return (MethodDeclaration) StaticJavaParser.parseBodyDeclaration(code);
   }

   private static void addDisabled(MethodDeclaration method, boolean disabledByDefault)
   {
      if (!disabledByDefault)
      {
         return;
      }
      method.addAnnotation(new SingleMemberAnnotationExpr(
               StaticJavaParser.parseName("Disabled"),
               new StringLiteralExpr("Generated by Quietly CRUD with disabledByDefault=true")
      ));
   }
}
