package ua.quietlymavenplugin.render;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.FieldAccessExpr;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.Name;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.SingleMemberAnnotationExpr;
import com.github.javaparser.ast.expr.StringLiteralExpr;
import org.apache.maven.plugin.logging.Log;
import ua.quietlycore.model.FilterInfo;
import ua.quietlymavenplugin.render.config.FieldResolutionMode;
import ua.quietlymavenplugin.render.javaparser.FieldResolutionResult;
import ua.quietlymavenplugin.render.javaparser.FieldResolver;
import ua.quietlymavenplugin.render.javaparser.dsl.MethodDsl;
import ua.quietlymavenplugin.render.javaparser.dsl.Quietly;

import java.lang.reflect.Field;

/**
 * AST Filter Tests Builder
 * Si occupa di generazione di codice dei test dei filtri
 */
public class FilterTestAstBuilder {

   /**
    * Costruisce il metodo di test per un filtro, con risoluzione fuzzy dei campi
    */
   public static MethodDeclaration buildFilterTestMethod(
            FilterInfo filter,
            Class<?> entityClass,
            Log log,
            FieldResolutionMode fieldResolutionMode,
            boolean disabledByDefault
   ) {
      String filterField = filter.field;
      String prefix = filter.prefix;

      FieldResolutionResult fieldResult = FieldResolver.resolveField(entityClass, filterField, fieldResolutionMode);
      if (log != null) {
         fieldResult.warnings().forEach(log::warn);
      }
      if (!fieldResult.resolved()) {
         throw new QuietlyGenerationException(
                  "Filter " + prefix + "." + filterField + " references field " + filterField
                           + ", but no deterministic field match was found on entity " + entityClass.getSimpleName()
                           + ". Use fieldResolutionMode=FUZZY or fix the filter metadata. Details: "
                           + String.join("; ", fieldResult.errors())
         );
      }

      Field realField = fieldResult.field().orElseThrow();
      String realFieldName = realField.getName();

      // tipo reale del campo (enum compresi)
      Class<?> realFieldType = realField.getType();

      String whereClause = realFieldName + " IS NOT NULL";

      var entityType = StaticJavaParser.parseClassOrInterfaceType(entityClass.getSimpleName());

      // costruzione metodo
      MethodDsl methodDsl = new MethodDsl("void", toJavaIdentifier(prefix + "_" + filterField + "_filter_test"))
               .public_()
               .markerAnnotation("Test")
               .annotation("TestSecurity")
               .param("user", "test")
               .apply();

      if (disabledByDefault) {
         methodDsl.build().addAnnotation(new SingleMemberAnnotationExpr(
                  new Name("Disabled"),
                  new StringLiteralExpr("Generated by Quietly with disabledByDefault=true")
         ));
      }

      if (filter.paramType != null) {

         // costruzione test_entity(...)
         Expression valueExpr = Quietly.dsl()
                  .call("test_entity")
                  .argumentName("em")
                  .argumentClass(entityType)
                  .argumentString(whereClause)
                  .field(realFieldName)
                  .build();

         // variabile tipizzata con il tipo reale del campo
         String typeName = typeName(realFieldType);

         // costruisce Assertions.assertNotNull(paramValue);
         MethodCallExpr assertNotNullCall = Quietly.dsl()
                  .call("Assertions.assertNotNull")
                  .argumentName("paramValue")
                  .buildCall();

         // costruisce assert_filter_works("obj.filtro", paramValue, Entity.class);
         MethodCallExpr assertCall = Quietly.dsl()
                  .call("assert_filter_works")
                  .argumentString(prefix + "." + filterField)
                  .argumentName("paramValue")
                  .argumentClass(entityType)
                  .buildCall();

         methodDsl.body(
                  Quietly.statements()
                           .var(typeName, "paramValue", valueExpr)
                           .stmt(assertNotNullCall)
                           .stmt(assertCall)
         );

      }
      else
      {
         // filtro senza parametro (nil/not_nil)
         MethodCallExpr assertCall = Quietly.dsl()
                  .call("assert_filter_works")
                  .argumentString(prefix + "." + filterField)
                  .argumentNull()
                  .argumentClass(entityType)
                  .buildCall();

         methodDsl.body(
                  Quietly.statements()
                           .stmt(assertCall)
         );
      }

      MethodDeclaration method = methodDsl.build();
      method.setJavadocComment("@quietly-generated filter=\"" + prefix + "." + filterField + "\"");
      return method;
   }

   private static String toJavaIdentifier(String value) {
      StringBuilder result = new StringBuilder();
      for (int i = 0; i < value.length(); i++) {
         char c = value.charAt(i);
         if (i == 0) {
            result.append(Character.isJavaIdentifierStart(c) ? c : '_');
         } else {
            result.append(Character.isJavaIdentifierPart(c) ? c : '_');
         }
      }
      return result.toString();
   }

   private static String typeName(Class<?> type) {
      if (type.isPrimitive()) {
         return type.getName();
      }
      if (type.getPackageName().equals("java.lang")) {
         return type.getSimpleName();
      }
      return type.getCanonicalName();
   }

   /**
    * Costruisce il metodo beforeEach() con caricamento sql, delete dei entity e update
    */
   public static MethodDeclaration buildBeforeEachMethod(Class<?> entityClass) {
      var entityType = StaticJavaParser.parseClassOrInterfaceType(entityClass.getSimpleName());

      // costruisce Entity.deleteAll();
      Expression deleteAllCall = Quietly.dsl()
               .staticCall(entityType, "deleteAll")
               .build();

      // costruisce SqlUtils.loadSqlFromClasspath("sql/" + Entity.TABLE_NAME + ".sql")
      Expression loadSqlCall = Quietly.dsl()
               .staticCall(
                        StaticJavaParser.parseClassOrInterfaceType("SqlUtils"),
                        "loadSqlFromClasspath")
               .argumentConcatenation(
                        "sql/",
                        new FieldAccessExpr(
                                 new NameExpr(entityType.asString()),
                                 "TABLE_NAME"),
                        ".sql")
               .build();

      // costruisce Entity.getEntityManager().createNativeQuery(SqlUtils.loadSqlFromClasspath("sql/" + Entity.TABLE_NAME + ".sql")).executeUpdate();
      Expression updateCall = Quietly.dsl()
               .staticCall(entityType, "getEntityManager")
               .callMethod("createNativeQuery")
               .argument(loadSqlCall)
               .callMethod("executeUpdate")
               .build();

      // costruisce il metodo intero
      MethodDsl methodDsl = Quietly.method("void", "beforeEach")
               .public_()
               .markerAnnotation("BeforeEach")
               .throws_("IOException")
               .annotation("Transactional")
               .singleMember(new NameExpr("Transactional.TxType.REQUIRES_NEW"))
               .apply()
               .body(
                        Quietly.statements()
                                 .stmt(deleteAllCall)
                                 .stmt(updateCall)
               );

      return methodDsl.build();
   }

   public static FieldDeclaration buildEntityManagerField() {
      // costruisce @Inject private EntityManager em;
      String code = "@Inject\nprivate EntityManager em;";
      return (FieldDeclaration) StaticJavaParser.parseBodyDeclaration(code);
   }

}
