package ua.quietlymavenplugin.render;

import com.acme.model.Customer;
import org.apache.maven.plugin.logging.SystemStreamLog;
import org.apache.maven.project.MavenProject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import ua.quietlycore.model.FilterEntityInfo;
import ua.quietlymavenplugin.render.config.FieldResolutionMode;
import ua.quietlymavenplugin.render.config.QuietlyPluginConfig;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class CrudTestsCodeGeneratorTest
{

   @TempDir
   Path tempDir;

   @Test
   public void generator_creates_crud_smoke_test_file() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      CrudTestsCodeGenerator generator = new CrudTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateCrudTests(List.of(new FilterEntityInfo(Customer.class, List.of())));

      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerCrudTest.java");
      String generated = Files.readString(generatedFile);

      assertTrue(generated.contains("public class CustomerCrudTest"));
      assertTrue(generated.contains("CustomerServiceRs.class"));
      assertTrue(generated.contains("@quietly-generated crud=\"list\""));
      assertTrue(generated.contains("@quietly-generated crud=\"get-missing\""));
      assertTrue(generated.contains("list_endpoint_returns_success_test"));
      assertTrue(generated.contains("get_missing_entity_returns_not_found_test"));
      assertFalse(generated.contains("@Disabled"));
   }

   @Test
   public void generator_adds_disabled_annotation_when_configured() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, true);
      CrudTestsCodeGenerator generator = new CrudTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateCrudTests(List.of(new FilterEntityInfo(Customer.class, List.of())));

      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerCrudTest.java");
      String generated = Files.readString(generatedFile);

      assertTrue(generated.contains("import org.junit.jupiter.api.Disabled;"));
      assertTrue(generated.contains("@Disabled(\"Generated by Quietly CRUD with disabledByDefault=true\")"));
   }

   @Test
   public void generator_does_not_duplicate_existing_crud_methods() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      CrudTestsCodeGenerator generator = new CrudTestsCodeGenerator(new SystemStreamLog(), project, config);
      List<FilterEntityInfo> entities = List.of(new FilterEntityInfo(Customer.class, List.of()));

      generator.generateCrudTests(entities);
      generator.generateCrudTests(entities);

      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerCrudTest.java");
      String generated = Files.readString(generatedFile);

      assertEquals(1, occurrences(generated, "list_endpoint_returns_success_test"));
      assertEquals(1, occurrences(generated, "get_missing_entity_returns_not_found_test"));
   }

   @Test
   public void generator_writes_crud_report_and_json_report() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      CrudTestsCodeGenerator generator = new CrudTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateCrudTests(List.of(new FilterEntityInfo(Customer.class, List.of())));

      String report = Files.readString(config.reportFile());
      String jsonReport = Files.readString(config.jsonReportFile());

      assertTrue(report.contains("# Quietly CRUD Generation Report"));
      assertTrue(report.contains("| Customer | CRUD_OPERATION | list | GENERATED |"));
      assertTrue(report.contains("| Customer | CRUD_OPERATION | get-missing | GENERATED |"));
      assertTrue(jsonReport.contains("\"capability\": \"CRUD_OPERATION\""));
      assertTrue(jsonReport.contains("\"subject\": \"list\""));
      assertTrue(jsonReport.contains("\"subject\": \"get-missing\""));
   }

   @Test
   public void missing_service_uses_domain_specific_error() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               "Missing${entitySimpleName}Service",
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("crud-report.md").toFile(),
               false,
               true,
               true,
               false,
               FieldResolutionMode.STRICT
      );
      CrudTestsCodeGenerator generator = new CrudTestsCodeGenerator(new SystemStreamLog(), project, config);

      QuietlyGenerationException exception = assertThrows(
               QuietlyGenerationException.class,
               () -> generator.generateCrudTests(List.of(new FilterEntityInfo(Customer.class, List.of())))
      );

      assertTrue(exception.getMessage().contains("no matching REST service for CRUD smoke tests"));
      assertTrue(exception.getMessage().contains("Configure servicePackagePattern/serviceNamePattern"));
   }

   private MavenProject project() throws Exception
   {
      TestMavenProject project = new TestMavenProject(List.of(testClassesPath()));
      File pom = tempDir.resolve("pom.xml").toFile();
      Files.writeString(pom.toPath(), "<project />");
      project.setFile(pom);
      return project;
   }

   private QuietlyPluginConfig config(MavenProject project, boolean disabledByDefault)
   {
      return new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               null,
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("crud-report.md").toFile(),
               disabledByDefault,
               true,
               true,
               false,
               FieldResolutionMode.STRICT
      );
   }

   private String testClassesPath()
   {
      return Path.of(Customer.class.getProtectionDomain().getCodeSource().getLocation().getPath()).toString();
   }

   private int occurrences(String text, String needle)
   {
      int count = 0;
      int index = 0;
      while ((index = text.indexOf(needle, index)) >= 0)
      {
         count++;
         index += needle.length();
      }
      return count;
   }

   private static class TestMavenProject extends MavenProject
   {

      private final List<String> compileClasspathElements;

      TestMavenProject(List<String> compileClasspathElements)
      {
         this.compileClasspathElements = compileClasspathElements;
      }

      @Override
      public List<String> getCompileClasspathElements()
      {
         return compileClasspathElements;
      }
   }
}
