package ua.quietlymavenplugin.render;

import com.acme.model.Customer;
import org.apache.maven.plugin.logging.SystemStreamLog;
import org.apache.maven.project.MavenProject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import ua.quietlycore.model.FilterEntityInfo;
import ua.quietlycore.model.FilterInfo;
import ua.quietlymavenplugin.render.config.FieldResolutionMode;
import ua.quietlymavenplugin.render.config.QuietlyPluginConfig;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class FilterTestsCodeGeneratorTest
{

   @TempDir
   Path tempDir;

   @Test
   public void generator_omits_disabled_annotation_by_default() throws Exception
   {
      Path generatedFile = generate(false);
      String generated = Files.readString(generatedFile);

      assertFalse(generated.contains("@Disabled"));
      assertFalse(generated.contains("import org.junit.jupiter.api.Disabled;"));
      assertTrue(generated.contains("@quietly-generated filter=\"obj.status\""));
   }

   @Test
   public void generator_adds_disabled_annotation_when_configured() throws Exception
   {
      Path generatedFile = generate(true);
      String generated = Files.readString(generatedFile);

      assertTrue(generated.contains("import org.junit.jupiter.api.Disabled;"));
      assertTrue(generated.contains("@Disabled(\"Generated by Quietly with disabledByDefault=true\")"));
   }

   @Test
   public void generator_does_not_duplicate_existing_generated_methods() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);
      List<FilterEntityInfo> entities = List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status"))));

      generator.generateFilterTests(entities);
      generator.generateFilterTests(entities);

      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      String generated = Files.readString(generatedFile);

      assertEquals(1, occurrences(generated, "obj_status_filter_test"));
   }

   @Test
   public void generator_adds_marker_to_existing_generated_method() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      Files.createDirectories(generatedFile.getParent());
      Files.writeString(generatedFile, """
               package com.acme;
               
               public class CustomerFiltersTest {
                   public void obj_status_filter_test() {
                   }
               }
               """);

      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);
      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      String generated = Files.readString(generatedFile);
      String report = Files.readString(config.reportFile());

      assertTrue(generated.contains("@quietly-generated filter=\"obj.status\""));
      assertEquals(1, occurrences(generated, "obj_status_filter_test"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | UPDATED_MARKER |"));
   }

   @Test
   public void missing_service_uses_domain_specific_error() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               "Missing${entitySimpleName}Service",
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("quietly-report.md").toFile(),
               false,
               true,
               true,
               false,
               FieldResolutionMode.STRICT
      );
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      QuietlyGenerationException exception = assertThrows(
               QuietlyGenerationException.class,
               () -> generator.generateFilterTests(
                        List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))))
      );

      assertTrue(exception.getMessage().contains("no matching REST service was found"));
      assertTrue(exception.getMessage().contains("Configure servicePackagePattern/serviceNamePattern"));

      String report = Files.readString(config.reportFile());
      assertTrue(report.contains("- Total filters: `1`"));
      assertTrue(report.contains("- Covered filters: `0`"));
      assertTrue(report.contains("- Generation coverage: `0.00%`"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | SKIPPED_MISSING_SERVICE |"));
   }

   @Test
   public void unresolved_field_can_be_skipped_when_configured() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               null,
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("quietly-report.md").toFile(),
               false,
               true,
               false,
               false,
               FieldResolutionMode.STRICT
      );
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(
               filter("obj", "status"),
               filter("obj", "missing")
      ))));

      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      String generated = Files.readString(generatedFile);

      assertTrue(generated.contains("obj_status_filter_test"));
      assertFalse(generated.contains("obj_missing_filter_test"));
   }

   @Test
   public void generator_writes_markdown_report() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      String report = Files.readString(config.reportFile());
      assertTrue(report.contains("# Quietly Filter Generation Report"));
      assertTrue(report.contains("- Total filters: `1`"));
      assertTrue(report.contains("- Covered filters: `1`"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | GENERATED |"));

      String jsonReport = Files.readString(config.jsonReportFile());
      assertTrue(jsonReport.contains("\"totalFilters\": 1"));
      assertTrue(jsonReport.contains("\"coveredFilters\": 1"));
      assertTrue(jsonReport.contains("\"status\": \"GENERATED\""));
   }

   @Test
   public void generator_reports_stale_generated_tests() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      Files.createDirectories(generatedFile.getParent());
      Files.writeString(generatedFile, """
               package com.acme;
               
               public class CustomerFiltersTest {
                   /**
                    * @quietly-generated filter="obj.oldStatus"
                    */
                   public void obj_oldStatus_filter_test() {
                   }
               }
               """);

      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);
      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      String report = Files.readString(config.reportFile());
      String jsonReport = Files.readString(config.jsonReportFile());

      assertTrue(report.contains("| Customer | FILTER_TEST | obj.oldStatus | STALE_GENERATED_TEST |"));
      assertTrue(jsonReport.contains("\"status\": \"STALE_GENERATED_TEST\""));
   }

   @Test
   public void dry_run_writes_report_but_does_not_write_generated_test_file() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               null,
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("quietly-report.md").toFile(),
               false,
               true,
               true,
               true,
               FieldResolutionMode.STRICT
      );
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      assertFalse(Files.exists(config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java")));
      assertTrue(Files.readString(config.reportFile()).contains("- Dry run: `true`"));
   }

   private Path generate(boolean disabledByDefault) throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, disabledByDefault);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      return config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
   }

   private MavenProject project() throws Exception
   {
      TestMavenProject project = new TestMavenProject(List.of(testClassesPath()));
      File pom = tempDir.resolve("pom.xml").toFile();
      Files.writeString(pom.toPath(), "<project />");
      project.setFile(pom);
      return project;
   }

   private QuietlyPluginConfig config(MavenProject project, boolean disabledByDefault)
   {
      return new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               null,
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("quietly-report.md").toFile(),
               disabledByDefault,
               true,
               true,
               false,
               FieldResolutionMode.STRICT
      );
   }

   private String testClassesPath()
   {
      return Path.of(Customer.class.getProtectionDomain().getCodeSource().getLocation().getPath()).toString();
   }

   private FilterInfo filter(String prefix, String field)
   {
      FilterInfo filter = new FilterInfo();
      filter.prefix = prefix;
      filter.field = field;
      filter.paramType = String.class;
      return filter;
   }

   private int occurrences(String text, String needle)
   {
      int count = 0;
      int index = 0;
      while ((index = text.indexOf(needle, index)) >= 0)
      {
         count++;
         index += needle.length();
      }
      return count;
   }

   private static class TestMavenProject extends MavenProject
   {

      private final List<String> compileClasspathElements;

      TestMavenProject(List<String> compileClasspathElements)
      {
         this.compileClasspathElements = compileClasspathElements;
      }

      @Override
      public List<String> getCompileClasspathElements()
      {
         return compileClasspathElements;
      }
   }
}
