package ua.quietlymavenplugin.render;

import com.acme.model.Customer;
import com.acme.model.DateCustomer;
import org.junit.jupiter.api.Test;
import ua.quietlycore.model.FilterInfo;
import ua.quietlymavenplugin.render.config.FieldResolutionMode;
import ua.quietlymavenplugin.render.javaparser.FieldResolutionResult;
import ua.quietlymavenplugin.render.javaparser.FieldResolver;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

public class FilterTestAstBuilderTest
{

   @Test
   public void generated_test_method_is_active_by_default()
   {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("obj", "status"),
               Customer.class,
               resolved(Customer.class, "status"),
               false
      ).toString();

      assertTrue(generated.contains("@Test"));
      assertFalse(generated.contains("@Disabled"));
   }

   @Test
   public void generated_test_method_can_be_disabled_with_reason()
   {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("obj", "status"),
               Customer.class,
               resolved(Customer.class, "status"),
               true
      ).toString();

      assertTrue(generated.contains("@Disabled(\"Generated by Quietly with disabledByDefault=true\")"));
   }

   @Test
   public void namespaced_filter_name_generates_valid_java_method_name()
   {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("customer.obj", "fornitore_uuid"),
               Customer.class,
               resolved(Customer.class, "fornitore_uuid"),
               false
      ).toString();

      assertTrue(generated.contains("customer_obj_fornitore_uuid_filter_test"));
      assertFalse(generated.contains("customer_obj.fornitore_uuid_filter_test"));
   }

   @Test
   public void non_java_lang_field_type_is_fully_qualified()
   {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("from", "dataRiferimento"),
               DateCustomer.class,
               resolved(DateCustomer.class, "dataRiferimento"),
               false
      ).toString();

      assertTrue(generated.contains("java.time.LocalDate paramValue"));
   }

   @Test
   public void builder_does_not_resolve_fields_or_raise_field_resolution_errors() throws Exception
   {
      String source = Files.readString(Path.of(
               "src/main/java/ua/quietlymavenplugin/render/FilterTestAstBuilder.java"
      ));

      assertFalse(source.contains("FieldResolver"));
      assertFalse(source.contains("QuietlyGenerationException"));
   }

   private FieldResolutionResult resolved(Class<?> entityClass, String field)
   {
      FieldResolutionResult result = FieldResolver.resolveField(entityClass, field, FieldResolutionMode.STRICT);
      assertTrue(result.resolved());
      return result;
   }

   private FilterInfo filter(String prefix, String field)
   {
      FilterInfo filter = new FilterInfo();
      filter.prefix = prefix;
      filter.field = field;
      filter.paramType = String.class;
      return filter;
   }
}
