package ua.quietlymavenplugin.render;

import com.acme.model.Customer;
import com.acme.model.DateCustomer;
import org.junit.jupiter.api.Test;
import ua.quietlycore.model.FilterInfo;
import ua.quietlymavenplugin.render.config.FieldResolutionMode;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FilterTestAstBuilderTest {

   @Test
   public void generated_test_method_is_active_by_default() {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("obj", "status"),
               Customer.class,
               null,
               FieldResolutionMode.STRICT,
               false
      ).toString();

      assertTrue(generated.contains("@Test"));
      assertFalse(generated.contains("@Disabled"));
   }

   @Test
   public void generated_test_method_can_be_disabled_with_reason() {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("obj", "status"),
               Customer.class,
               null,
               FieldResolutionMode.STRICT,
               true
      ).toString();

      assertTrue(generated.contains("@Disabled(\"Generated by Quietly with disabledByDefault=true\")"));
   }

   @Test
   public void namespaced_filter_name_generates_valid_java_method_name() {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("customer.obj", "fornitore_uuid"),
               Customer.class,
               null,
               FieldResolutionMode.STRICT,
               false
      ).toString();

      assertTrue(generated.contains("customer_obj_fornitore_uuid_filter_test"));
      assertFalse(generated.contains("customer_obj.fornitore_uuid_filter_test"));
   }

   @Test
   public void non_java_lang_field_type_is_fully_qualified() {
      String generated = FilterTestAstBuilder.buildFilterTestMethod(
               filter("from", "dataRiferimento"),
               DateCustomer.class,
               null,
               FieldResolutionMode.STRICT,
               false
      ).toString();

      assertTrue(generated.contains("java.time.LocalDate paramValue"));
   }

   @Test
   public void unresolved_field_uses_domain_specific_error() {
      QuietlyGenerationException exception = assertThrows(
               QuietlyGenerationException.class,
               () -> FilterTestAstBuilder.buildFilterTestMethod(
                        filter("obj", "missing"),
                        Customer.class,
                        null,
                        FieldResolutionMode.STRICT,
                        false
               )
      );

      assertTrue(exception.getMessage().contains("Use fieldResolutionMode=FUZZY or fix the filter metadata"));
   }

   private FilterInfo filter(String prefix, String field) {
      FilterInfo filter = new FilterInfo();
      filter.prefix = prefix;
      filter.field = field;
      filter.paramType = String.class;
      return filter;
   }
}
