package ua.quietlymavenplugin.render;

import com.acme.model.AmbiguousCustomer;
import com.acme.model.Customer;
import org.apache.maven.plugin.logging.SystemStreamLog;
import org.apache.maven.project.MavenProject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import ua.quietlycore.model.FilterEntityInfo;
import ua.quietlycore.model.FilterInfo;
import ua.quietlymavenplugin.discovery.DiscoveredProject;
import ua.quietlymavenplugin.plan.DoctorPlanner;
import ua.quietlymavenplugin.plan.GenerationPlan;
import ua.quietlymavenplugin.plan.PlanState;
import ua.quietlymavenplugin.render.config.FieldResolutionMode;
import ua.quietlymavenplugin.render.config.QuietlyPluginConfig;
import ua.quietlymavenplugin.render.report.QuietlyReport;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class FilterTestsCodeGeneratorTest
{

   @TempDir
   Path tempDir;

   @Test
   public void generator_omits_disabled_annotation_by_default() throws Exception
   {
      Path generatedFile = generate(false);
      String generated = Files.readString(generatedFile);

      assertFalse(generated.contains("@Disabled"));
      assertFalse(generated.contains("import org.junit.jupiter.api.Disabled;"));
      assertTrue(generated.contains("@quietly-generated filter=\"obj.status\""));
   }

   @Test
   public void generator_adds_disabled_annotation_when_configured() throws Exception
   {
      Path generatedFile = generate(true);
      String generated = Files.readString(generatedFile);

      assertTrue(generated.contains("import org.junit.jupiter.api.Disabled;"));
      assertTrue(generated.contains("@Disabled(\"Generated by Quietly with disabledByDefault=true\")"));
   }

   @Test
   public void generator_does_not_duplicate_existing_generated_methods() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);
      List<FilterEntityInfo> entities = List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status"))));

      generator.generateFilterTests(entities);
      generator.generateFilterTests(entities);

      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      String generated = Files.readString(generatedFile);

      assertEquals(1, occurrences(generated, "obj_status_filter_test"));
   }

   @Test
   public void generator_adds_marker_to_existing_generated_method() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      Files.createDirectories(generatedFile.getParent());
      Files.writeString(generatedFile, """
               package com.acme;
               
               public class CustomerFiltersTest {
                   public void obj_status_filter_test() {
                   }
               }
               """);

      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);
      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      String generated = Files.readString(generatedFile);
      String report = Files.readString(config.reportFile());

      assertTrue(generated.contains("@quietly-generated filter=\"obj.status\""));
      assertEquals(1, occurrences(generated, "obj_status_filter_test"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | UPDATED_MARKER |"));
   }

   @Test
   public void missing_service_uses_domain_specific_error() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               "Missing${entitySimpleName}Service",
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("quietly-report.md").toFile(),
               false,
               true,
               true,
               false,
               FieldResolutionMode.STRICT
      );
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      QuietlyGenerationException exception = assertThrows(
               QuietlyGenerationException.class,
               () -> generator.generateFilterTests(
                        List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))))
      );

      assertTrue(exception.getMessage().contains("no matching REST service was found"));
      assertTrue(exception.getMessage().contains("Configure servicePackagePattern/serviceNamePattern"));

      String report = Files.readString(config.reportFile());
      assertTrue(report.contains("- Discovered filters: `1`"));
      assertTrue(report.contains("- Generatable filters: `0`"));
      assertTrue(report.contains("- Generation readiness: `0.00%`"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | SKIPPED_MISSING_SERVICE |"));
   }

   @Test
   public void unresolved_field_can_be_skipped_when_configured() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               null,
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("quietly-report.md").toFile(),
               false,
               true,
               false,
               false,
               FieldResolutionMode.STRICT
      );
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(
               filter("obj", "status"),
               filter("obj", "missing")
      ))));

      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      String generated = Files.readString(generatedFile);

      assertTrue(generated.contains("obj_status_filter_test"));
      assertFalse(generated.contains("obj_missing_filter_test"));
   }

   @Test
   public void unresolved_field_uses_domain_specific_error_before_rendering() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      QuietlyGenerationException exception = assertThrows(
               QuietlyGenerationException.class,
               () -> generator.generateFilterTests(
                        List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "missing")))))
      );

      assertTrue(exception.getMessage().contains("Use fieldResolutionMode=FUZZY or fix the filter metadata"));
      assertFalse(Files.readString(config.reportFile()).contains("obj_missing_filter_test"));
   }

   @Test
   public void doctor_and_filter_tests_agree_on_missing_field_resolution() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig doctorConfig = config(project, false, "doctor-report.md", false, true,
               FieldResolutionMode.STRICT);
      QuietlyProjectAnalyzer analyzer = new QuietlyProjectAnalyzer(new SystemStreamLog(), project, doctorConfig);

      QuietlyReport doctorReport = analyzer.doctor(List.of(
               new FilterEntityInfo(Customer.class, List.of(filter("obj", "missing")))
      ));

      QuietlyPluginConfig generatorConfig = config(project, false, "generator-report.md", false, false,
               FieldResolutionMode.STRICT);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project,
               generatorConfig);
      generator.generateFilterTests(List.of(
               new FilterEntityInfo(Customer.class, List.of(filter("obj", "missing")))
      ));

      String generatorReport = Files.readString(generatorConfig.reportFile());
      assertEquals("SKIPPED_UNRESOLVED_FIELD", doctorReport.entries().stream()
               .filter(entry -> entry.subject().equals("obj.missing"))
               .findFirst()
               .orElseThrow()
               .status());
      assertTrue(generatorReport.contains("| Customer | FILTER_TEST | obj.missing | SKIPPED_UNRESOLVED_FIELD |"));
      assertFalse(generatorReport.contains("obj_missing_filter_test"));
   }

   @Test
   public void doctor_and_filter_tests_agree_on_strict_ambiguous_field_resolution() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig doctorConfig = config(project, false, "doctor-ambiguous-report.md", false, true,
               FieldResolutionMode.STRICT);
      QuietlyProjectAnalyzer analyzer = new QuietlyProjectAnalyzer(new SystemStreamLog(), project, doctorConfig);

      QuietlyReport doctorReport = analyzer.doctor(List.of(
               new FilterEntityInfo(AmbiguousCustomer.class, List.of(filter("obj", "code")))
      ));

      QuietlyPluginConfig generatorConfig = config(project, false, "generator-ambiguous-report.md", false, false,
               FieldResolutionMode.STRICT);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project,
               generatorConfig);
      generator.generateFilterTests(List.of(
               new FilterEntityInfo(AmbiguousCustomer.class, List.of(filter("obj", "code")))
      ));

      String generatorReport = Files.readString(generatorConfig.reportFile());
      assertEquals("SKIPPED_UNRESOLVED_FIELD", doctorReport.entries().stream()
               .filter(entry -> entry.subject().equals("obj.code"))
               .findFirst()
               .orElseThrow()
               .status());
      assertTrue(generatorReport.contains("| AmbiguousCustomer | FILTER_TEST | obj.code | SKIPPED_UNRESOLVED_FIELD |"));
      assertFalse(generatorReport.contains("obj_code_filter_test"));
   }

   @Test
   public void generator_writes_markdown_report() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      String report = Files.readString(config.reportFile());
      assertTrue(report.contains("# Quietly Filter Generation Report"));
      assertTrue(report.contains("- Discovered filters: `1`"));
      assertTrue(report.contains("- Generated test methods: `1`"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | GENERATED |"));

      String jsonReport = Files.readString(config.jsonReportFile());
      assertTrue(jsonReport.contains("\"totalFilters\": 1"));
      assertTrue(jsonReport.contains("\"coveredFilters\": 1"));
      assertTrue(jsonReport.contains("\"status\": \"GENERATED\""));
   }

   @Test
   public void generator_reports_stale_generated_tests() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      Path generatedFile = config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
      Files.createDirectories(generatedFile.getParent());
      Files.writeString(generatedFile, """
               package com.acme;
               
               public class CustomerFiltersTest {
                   /**
                    * @quietly-generated filter="obj.oldStatus"
                    */
                   public void obj_oldStatus_filter_test() {
                   }
               }
               """);

      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);
      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      String report = Files.readString(config.reportFile());
      String jsonReport = Files.readString(config.jsonReportFile());

      assertTrue(report.contains("| Customer | FILTER_TEST | obj.oldStatus | STALE_GENERATED_TEST |"));
      assertTrue(jsonReport.contains("\"status\": \"STALE_GENERATED_TEST\""));
   }

   @Test
   public void generator_uses_plan_readiness_without_treating_fixture_diagnostic_as_generation_blocker()
            throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, false);
      List<FilterEntityInfo> entities = List.of(
               new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))
      );
      GenerationPlan plan = new DoctorPlanner(project, config)
               .plan(new DiscoveredProject(config.moduleContext(), entities));

      assertEquals(PlanState.READY, plan.entries().stream()
               .filter(entry -> entry.subject().equals("obj.status"))
               .filter(entry -> !entry.diagnostic())
               .findFirst()
               .orElseThrow()
               .state());
      assertEquals(PlanState.BLOCKED, plan.entries().stream()
               .filter(entry -> entry.subject().equals("table-name"))
               .findFirst()
               .orElseThrow()
               .state());

      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);
      generator.generateFilterTests(entities);

      String report = Files.readString(config.reportFile());
      String generated = Files.readString(config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | GENERATED |"));
      assertFalse(report.contains("MISSING_TABLE_NAME"));
      assertTrue(generated.contains("obj_status_filter_test"));
   }

   @Test
   public void dry_run_writes_report_but_does_not_write_generated_test_file() throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               null,
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve("quietly-report.md").toFile(),
               false,
               true,
               true,
               true,
               FieldResolutionMode.STRICT
      );
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      assertFalse(Files.exists(config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java")));
      String report = Files.readString(config.reportFile());
      assertTrue(report.contains("- Dry run: `true`"));
      assertTrue(report.contains("- Generatable filters: `1`"));
      assertTrue(report.contains("- Generated test methods: `0`"));
      assertTrue(report.contains("| Customer | FILTER_TEST | obj.status | WOULD_GENERATE |"));
   }

   private Path generate(boolean disabledByDefault) throws Exception
   {
      MavenProject project = project();
      QuietlyPluginConfig config = config(project, disabledByDefault);
      FilterTestsCodeGenerator generator = new FilterTestsCodeGenerator(new SystemStreamLog(), project, config);

      generator.generateFilterTests(List.of(new FilterEntityInfo(Customer.class, List.of(filter("obj", "status")))));

      return config.testOutputDirectory().resolve("com/acme/CustomerFiltersTest.java");
   }

   private MavenProject project() throws Exception
   {
      TestMavenProject project = new TestMavenProject(List.of(testClassesPath()));
      File pom = tempDir.resolve("pom.xml").toFile();
      Files.writeString(pom.toPath(), "<project />");
      project.setFile(pom);
      return project;
   }

   private QuietlyPluginConfig config(MavenProject project, boolean disabledByDefault)
   {
      return config(project, disabledByDefault, "quietly-report.md", true, true, FieldResolutionMode.STRICT);
   }

   private QuietlyPluginConfig config(
            MavenProject project,
            boolean disabledByDefault,
            String reportName,
            boolean failOnMissingService,
            boolean failOnUnresolvedField,
            FieldResolutionMode fieldResolutionMode
   )
   {
      return new QuietlyPluginConfig(
               project,
               null,
               null,
               null,
               null,
               tempDir.resolve("generated-tests").toFile(),
               tempDir.resolve(reportName).toFile(),
               disabledByDefault,
               failOnMissingService,
               failOnUnresolvedField,
               false,
               fieldResolutionMode
      );
   }

   private String testClassesPath()
   {
      return Path.of(Customer.class.getProtectionDomain().getCodeSource().getLocation().getPath()).toString();
   }

   private FilterInfo filter(String prefix, String field)
   {
      FilterInfo filter = new FilterInfo();
      filter.prefix = prefix;
      filter.field = field;
      filter.paramType = String.class;
      return filter;
   }

   private int occurrences(String text, String needle)
   {
      int count = 0;
      int index = 0;
      while ((index = text.indexOf(needle, index)) >= 0)
      {
         count++;
         index += needle.length();
      }
      return count;
   }

   private static class TestMavenProject extends MavenProject
   {

      private final List<String> compileClasspathElements;

      TestMavenProject(List<String> compileClasspathElements)
      {
         this.compileClasspathElements = compileClasspathElements;
      }

      @Override
      public List<String> getCompileClasspathElements()
      {
         return compileClasspathElements;
      }
   }
}
